using entities;
namespace infrastructure.databases.seed;

/// <summary>
/// Provides a static collection of country data.
/// </summary>
public static class Countries
{
    /// <summary>
    /// Gets list of countries.
    /// </summary>
    public static List<Country> data;

    /// <summary>
    /// Initializes the <see cref="Countries"/> class.
    /// </summary>
    static Countries()
    {
        data = new List<Country>(new[]{ new Country { Id = 1, Name = "Afghanistan", Iso3 = "AFG", Iso2 = "AF", NumericCode = "004", PhoneCode = "93", Capital = "Kabul", Currency = new Currency(code: "AFN", name: "Afghan afghani", symbol: "؋"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 33.00000000, longitude: 65.00000000)}
        , new Country { Id = 2, Name = "Aland Islands", Iso3 = "ALA", Iso2 = "AX", NumericCode = "248", PhoneCode = "+358-18", Capital = "Mariehamn", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 60.11666700, longitude: 19.90000000)}
        , new Country { Id = 3, Name = "Albania", Iso3 = "ALB", Iso2 = "AL", NumericCode = "008", PhoneCode = "355", Capital = "Tirana", Currency = new Currency(code: "ALL", name: "Albanian lek", symbol: "Lek"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 41.00000000, longitude: 20.00000000)}
        , new Country { Id = 4, Name = "Algeria", Iso3 = "DZA", Iso2 = "DZ", NumericCode = "012", PhoneCode = "213", Capital = "Algiers", Currency = new Currency(code: "DZD", name: "Algerian dinar", symbol: "دج"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 28.00000000, longitude: 3.00000000)}
        , new Country { Id = 5, Name = "American Samoa", Iso3 = "ASM", Iso2 = "AS", NumericCode = "016", PhoneCode = "+1-684", Capital = "Pago Pago", Currency = new Currency(code: "USD", name: "US Dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -14.33333333, longitude: -170.00000000)}
        , new Country { Id = 6, Name = "Andorra", Iso3 = "AND", Iso2 = "AD", NumericCode = "020", PhoneCode = "376", Capital = "Andorra la Vella", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 42.50000000, longitude: 1.50000000)}
        , new Country { Id = 7, Name = "Angola", Iso3 = "AGO", Iso2 = "AO", NumericCode = "024", PhoneCode = "244", Capital = "Luanda", Currency = new Currency(code: "AOA", name: "Angolan kwanza", symbol: "Kz"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: -12.50000000, longitude: 18.50000000)}
        , new Country { Id = 8, Name = "Anguilla", Iso3 = "AIA", Iso2 = "AI", NumericCode = "660", PhoneCode = "+1-264", Capital = "The Valley", Currency = new Currency(code: "XCD", name: "East Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.25000000, longitude: -63.16666666)}
        , new Country { Id = 9, Name = "Antarctica", Iso3 = "ATA", Iso2 = "AQ", NumericCode = "010", PhoneCode = "672", Capital = "", Currency = new Currency(code: "AAD", name: "Antarctican dollar", symbol: "$"), Region = new Region(name: "Polar", subregion: ""), GeoLocation = new GeoLocation(latitude: -74.65000000, longitude: 4.48000000)}
        , new Country { Id = 10, Name = "Antigua And Barbuda", Iso3 = "ATG", Iso2 = "AG", NumericCode = "028", PhoneCode = "+1-268", Capital = "St. John's", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 17.05000000, longitude: -61.80000000)}
        , new Country { Id = 11, Name = "Argentina", Iso3 = "ARG", Iso2 = "AR", NumericCode = "032", PhoneCode = "54", Capital = "Buenos Aires", Currency = new Currency(code: "ARS", name: "Argentine peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -34.00000000, longitude: -64.00000000)}
        , new Country { Id = 12, Name = "Armenia", Iso3 = "ARM", Iso2 = "AM", NumericCode = "051", PhoneCode = "374", Capital = "Yerevan", Currency = new Currency(code: "AMD", name: "Armenian dram", symbol: "֏"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 40.00000000, longitude: 45.00000000)}
        , new Country { Id = 13, Name = "Aruba", Iso3 = "ABW", Iso2 = "AW", NumericCode = "533", PhoneCode = "297", Capital = "Oranjestad", Currency = new Currency(code: "AWG", name: "Aruban florin", symbol: "ƒ"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 12.50000000, longitude: -69.96666666)}
        , new Country { Id = 14, Name = "Australia", Iso3 = "AUS", Iso2 = "AU", NumericCode = "036", PhoneCode = "61", Capital = "Canberra", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Australia and New Zealand"), GeoLocation = new GeoLocation(latitude: -27.00000000, longitude: 133.00000000)}
        , new Country { Id = 15, Name = "Austria", Iso3 = "AUT", Iso2 = "AT", NumericCode = "040", PhoneCode = "43", Capital = "Vienna", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 47.33333333, longitude: 13.33333333)}
        , new Country { Id = 16, Name = "Azerbaijan", Iso3 = "AZE", Iso2 = "AZ", NumericCode = "031", PhoneCode = "994", Capital = "Baku", Currency = new Currency(code: "AZN", name: "Azerbaijani manat", symbol: "m"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 40.50000000, longitude: 47.50000000)}
        , new Country { Id = 18, Name = "Bahrain", Iso3 = "BHR", Iso2 = "BH", NumericCode = "048", PhoneCode = "973", Capital = "Manama", Currency = new Currency(code: "BHD", name: "Bahraini dinar", symbol: ".د.ب"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 26.00000000, longitude: 50.55000000)}
        , new Country { Id = 19, Name = "Bangladesh", Iso3 = "BGD", Iso2 = "BD", NumericCode = "050", PhoneCode = "880", Capital = "Dhaka", Currency = new Currency(code: "BDT", name: "Bangladeshi taka", symbol: "৳"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 24.00000000, longitude: 90.00000000)}
        , new Country { Id = 20, Name = "Barbados", Iso3 = "BRB", Iso2 = "BB", NumericCode = "052", PhoneCode = "+1-246", Capital = "Bridgetown", Currency = new Currency(code: "BBD", name: "Barbadian dollar", symbol: "Bds$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 13.16666666, longitude: -59.53333333)}
        , new Country { Id = 21, Name = "Belarus", Iso3 = "BLR", Iso2 = "BY", NumericCode = "112", PhoneCode = "375", Capital = "Minsk", Currency = new Currency(code: "BYN", name: "Belarusian ruble", symbol: "Br"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 53.00000000, longitude: 28.00000000)}
        , new Country { Id = 22, Name = "Belgium", Iso3 = "BEL", Iso2 = "BE", NumericCode = "056", PhoneCode = "32", Capital = "Brussels", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 50.83333333, longitude: 4.00000000)}
        , new Country { Id = 23, Name = "Belize", Iso3 = "BLZ", Iso2 = "BZ", NumericCode = "084", PhoneCode = "501", Capital = "Belmopan", Currency = new Currency(code: "BZD", name: "Belize dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 17.25000000, longitude: -88.75000000)}
        , new Country { Id = 24, Name = "Benin", Iso3 = "BEN", Iso2 = "BJ", NumericCode = "204", PhoneCode = "229", Capital = "Porto-Novo", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 9.50000000, longitude: 2.25000000)}
        , new Country { Id = 25, Name = "Bermuda", Iso3 = "BMU", Iso2 = "BM", NumericCode = "060", PhoneCode = "+1-441", Capital = "Hamilton", Currency = new Currency(code: "BMD", name: "Bermudian dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Northern America"), GeoLocation = new GeoLocation(latitude: 32.33333333, longitude: -64.75000000)}
        , new Country { Id = 26, Name = "Bhutan", Iso3 = "BTN", Iso2 = "BT", NumericCode = "064", PhoneCode = "975", Capital = "Thimphu", Currency = new Currency(code: "BTN", name: "Bhutanese ngultrum", symbol: "Nu."), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 27.50000000, longitude: 90.50000000)}
        , new Country { Id = 27, Name = "Bolivia", Iso3 = "BOL", Iso2 = "BO", NumericCode = "068", PhoneCode = "591", Capital = "Sucre", Currency = new Currency(code: "BOB", name: "Bolivian boliviano", symbol: "Bs."), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -17.00000000, longitude: -65.00000000)}
        , new Country { Id = 155, Name = "Bonaire, Sint Eustatius and Saba", Iso3 = "BES", Iso2 = "BQ", NumericCode = "535", PhoneCode = "599", Capital = "Kralendijk", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 12.15000000, longitude: -68.26666700)}
        , new Country { Id = 28, Name = "Bosnia and Herzegovina", Iso3 = "BIH", Iso2 = "BA", NumericCode = "070", PhoneCode = "387", Capital = "Sarajevo", Currency = new Currency(code: "BAM", name: "Bosnia and Herzegovina convertible mark", symbol: "KM"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 44.00000000, longitude: 18.00000000)}
        , new Country { Id = 29, Name = "Botswana", Iso3 = "BWA", Iso2 = "BW", NumericCode = "072", PhoneCode = "267", Capital = "Gaborone", Currency = new Currency(code: "BWP", name: "Botswana pula", symbol: "P"), Region = new Region(name: "Africa", subregion: "Southern Africa"), GeoLocation = new GeoLocation(latitude: -22.00000000, longitude: 24.00000000)}
        , new Country { Id = 30, Name = "Bouvet Island", Iso3 = "BVT", Iso2 = "BV", NumericCode = "074", PhoneCode = "0055", Capital = "", Currency = new Currency(code: "NOK", name: "Norwegian Krone", symbol: "kr"), Region = new Region(name: "", subregion: ""), GeoLocation = new GeoLocation(latitude: -54.43333333, longitude: 3.40000000)}
        , new Country { Id = 31, Name = "Brazil", Iso3 = "BRA", Iso2 = "BR", NumericCode = "076", PhoneCode = "55", Capital = "Brasilia", Currency = new Currency(code: "BRL", name: "Brazilian real", symbol: "R$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -10.00000000, longitude: -55.00000000)}
        , new Country { Id = 32, Name = "British Indian Ocean Territory", Iso3 = "IOT", Iso2 = "IO", NumericCode = "086", PhoneCode = "246", Capital = "Diego Garcia", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -6.00000000, longitude: 71.50000000)}
        , new Country { Id = 33, Name = "Brunei", Iso3 = "BRN", Iso2 = "BN", NumericCode = "096", PhoneCode = "673", Capital = "Bandar Seri Begawan", Currency = new Currency(code: "BND", name: "Brunei dollar", symbol: "B$"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 4.50000000, longitude: 114.66666666)}
        , new Country { Id = 34, Name = "Bulgaria", Iso3 = "BGR", Iso2 = "BG", NumericCode = "100", PhoneCode = "359", Capital = "Sofia", Currency = new Currency(code: "BGN", name: "Bulgarian lev", symbol: "Лв."), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 43.00000000, longitude: 25.00000000)}
        , new Country { Id = 35, Name = "Burkina Faso", Iso3 = "BFA", Iso2 = "BF", NumericCode = "854", PhoneCode = "226", Capital = "Ouagadougou", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 13.00000000, longitude: -2.00000000)}
        , new Country { Id = 36, Name = "Burundi", Iso3 = "BDI", Iso2 = "BI", NumericCode = "108", PhoneCode = "257", Capital = "Bujumbura", Currency = new Currency(code: "BIF", name: "Burundian franc", symbol: "FBu"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -3.50000000, longitude: 30.00000000)}
        , new Country { Id = 37, Name = "Cambodia", Iso3 = "KHM", Iso2 = "KH", NumericCode = "116", PhoneCode = "855", Capital = "Phnom Penh", Currency = new Currency(code: "KHR", name: "Cambodian riel", symbol: "KHR"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 13.00000000, longitude: 105.00000000)}
        , new Country { Id = 38, Name = "Cameroon", Iso3 = "CMR", Iso2 = "CM", NumericCode = "120", PhoneCode = "237", Capital = "Yaounde", Currency = new Currency(code: "XAF", name: "Central African CFA franc", symbol: "FCFA"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 6.00000000, longitude: 12.00000000)}
        , new Country { Id = 39, Name = "Canada", Iso3 = "CAN", Iso2 = "CA", NumericCode = "124", PhoneCode = "1", Capital = "Ottawa", Currency = new Currency(code: "CAD", name: "Canadian dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Northern America"), GeoLocation = new GeoLocation(latitude: 60.00000000, longitude: -95.00000000)}
        , new Country { Id = 40, Name = "Cape Verde", Iso3 = "CPV", Iso2 = "CV", NumericCode = "132", PhoneCode = "238", Capital = "Praia", Currency = new Currency(code: "CVE", name: "Cape Verdean escudo", symbol: "$"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 16.00000000, longitude: -24.00000000)}
        , new Country { Id = 41, Name = "Cayman Islands", Iso3 = "CYM", Iso2 = "KY", NumericCode = "136", PhoneCode = "+1-345", Capital = "George Town", Currency = new Currency(code: "KYD", name: "Cayman Islands dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 19.50000000, longitude: -80.50000000)}
        , new Country { Id = 42, Name = "Central African Republic", Iso3 = "CAF", Iso2 = "CF", NumericCode = "140", PhoneCode = "236", Capital = "Bangui", Currency = new Currency(code: "XAF", name: "Central African CFA franc", symbol: "FCFA"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 7.00000000, longitude: 21.00000000)}
        , new Country { Id = 43, Name = "Chad", Iso3 = "TCD", Iso2 = "TD", NumericCode = "148", PhoneCode = "235", Capital = "N'Djamena", Currency = new Currency(code: "XAF", name: "Central African CFA franc", symbol: "FCFA"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 15.00000000, longitude: 19.00000000)}
        , new Country { Id = 44, Name = "Chile", Iso3 = "CHL", Iso2 = "CL", NumericCode = "152", PhoneCode = "56", Capital = "Santiago", Currency = new Currency(code: "CLP", name: "Chilean peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -30.00000000, longitude: -71.00000000)}
        , new Country { Id = 45, Name = "China", Iso3 = "CHN", Iso2 = "CN", NumericCode = "156", PhoneCode = "86", Capital = "Beijing", Currency = new Currency(code: "CNY", name: "Chinese yuan", symbol: "¥"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 35.00000000, longitude: 105.00000000)}
        , new Country { Id = 46, Name = "Christmas Island", Iso3 = "CXR", Iso2 = "CX", NumericCode = "162", PhoneCode = "61", Capital = "Flying Fish Cove", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Australia and New Zealand"), GeoLocation = new GeoLocation(latitude: -10.50000000, longitude: 105.66666666)}
        , new Country { Id = 47, Name = "Cocos (Keeling) Islands", Iso3 = "CCK", Iso2 = "CC", NumericCode = "166", PhoneCode = "61", Capital = "West Island", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Australia and New Zealand"), GeoLocation = new GeoLocation(latitude: -12.50000000, longitude: 96.83333333)}
        , new Country { Id = 48, Name = "Colombia", Iso3 = "COL", Iso2 = "CO", NumericCode = "170", PhoneCode = "57", Capital = "Bogotá", Currency = new Currency(code: "COP", name: "Colombian peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: 4.00000000, longitude: -72.00000000)}
        , new Country { Id = 49, Name = "Comoros", Iso3 = "COM", Iso2 = "KM", NumericCode = "174", PhoneCode = "269", Capital = "Moroni", Currency = new Currency(code: "KMF", name: "Comorian franc", symbol: "CF"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -12.16666666, longitude: 44.25000000)}
        , new Country { Id = 50, Name = "Congo", Iso3 = "COG", Iso2 = "CG", NumericCode = "178", PhoneCode = "242", Capital = "Brazzaville", Currency = new Currency(code: "XAF", name: "Central African CFA franc", symbol: "FC"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: -1.00000000, longitude: 15.00000000)}
        , new Country { Id = 52, Name = "Cook Islands", Iso3 = "COK", Iso2 = "CK", NumericCode = "184", PhoneCode = "682", Capital = "Avarua", Currency = new Currency(code: "NZD", name: "Cook Islands dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -21.23333333, longitude: -159.76666666)}
        , new Country { Id = 53, Name = "Costa Rica", Iso3 = "CRI", Iso2 = "CR", NumericCode = "188", PhoneCode = "506", Capital = "San Jose", Currency = new Currency(code: "CRC", name: "Costa Rican colón", symbol: "₡"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 10.00000000, longitude: -84.00000000)}
        , new Country { Id = 54, Name = "Cote D'Ivoire (Ivory Coast)", Iso3 = "CIV", Iso2 = "CI", NumericCode = "384", PhoneCode = "225", Capital = "Yamoussoukro", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 8.00000000, longitude: -5.00000000)}
        , new Country { Id = 55, Name = "Croatia", Iso3 = "HRV", Iso2 = "HR", NumericCode = "191", PhoneCode = "385", Capital = "Zagreb", Currency = new Currency(code: "HRK", name: "Croatian kuna", symbol: "kn"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 45.16666666, longitude: 15.50000000)}
        , new Country { Id = 56, Name = "Cuba", Iso3 = "CUB", Iso2 = "CU", NumericCode = "192", PhoneCode = "53", Capital = "Havana", Currency = new Currency(code: "CUP", name: "Cuban peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 21.50000000, longitude: -80.00000000)}
        , new Country { Id = 249, Name = "Curaçao", Iso3 = "CUW", Iso2 = "CW", NumericCode = "531", PhoneCode = "599", Capital = "Willemstad", Currency = new Currency(code: "ANG", name: "Netherlands Antillean guilder", symbol: "ƒ"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 12.11666700, longitude: -68.93333300)}
        , new Country { Id = 57, Name = "Cyprus", Iso3 = "CYP", Iso2 = "CY", NumericCode = "196", PhoneCode = "357", Capital = "Nicosia", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 35.00000000, longitude: 33.00000000)}
        , new Country { Id = 58, Name = "Czech Republic", Iso3 = "CZE", Iso2 = "CZ", NumericCode = "203", PhoneCode = "420", Capital = "Prague", Currency = new Currency(code: "CZK", name: "Czech koruna", symbol: "Kč"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 49.75000000, longitude: 15.50000000)}
        , new Country { Id = 51, Name = "Democratic Republic of the Congo", Iso3 = "COD", Iso2 = "CD", NumericCode = "180", PhoneCode = "243", Capital = "Kinshasa", Currency = new Currency(code: "CDF", name: "Congolese Franc", symbol: "FC"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 0.00000000, longitude: 25.00000000)}
        , new Country { Id = 59, Name = "Denmark", Iso3 = "DNK", Iso2 = "DK", NumericCode = "208", PhoneCode = "45", Capital = "Copenhagen", Currency = new Currency(code: "DKK", name: "Danish krone", symbol: "Kr."), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 56.00000000, longitude: 10.00000000)}
        , new Country { Id = 60, Name = "Djibouti", Iso3 = "DJI", Iso2 = "DJ", NumericCode = "262", PhoneCode = "253", Capital = "Djibouti", Currency = new Currency(code: "DJF", name: "Djiboutian franc", symbol: "Fdj"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: 11.50000000, longitude: 43.00000000)}
        , new Country { Id = 61, Name = "Dominica", Iso3 = "DMA", Iso2 = "DM", NumericCode = "212", PhoneCode = "+1-767", Capital = "Roseau", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 15.41666666, longitude: -61.33333333)}
        , new Country { Id = 62, Name = "Dominican Republic", Iso3 = "DOM", Iso2 = "DO", NumericCode = "214", PhoneCode = "+1-809 and 1-829", Capital = "Santo Domingo", Currency = new Currency(code: "DOP", name: "Dominican peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 19.00000000, longitude: -70.66666666)}
        , new Country { Id = 63, Name = "East Timor", Iso3 = "TLS", Iso2 = "TL", NumericCode = "626", PhoneCode = "670", Capital = "Dili", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: -8.83333333, longitude: 125.91666666)}
        , new Country { Id = 64, Name = "Ecuador", Iso3 = "ECU", Iso2 = "EC", NumericCode = "218", PhoneCode = "593", Capital = "Quito", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -2.00000000, longitude: -77.50000000)}
        , new Country { Id = 65, Name = "Egypt", Iso3 = "EGY", Iso2 = "EG", NumericCode = "818", PhoneCode = "20", Capital = "Cairo", Currency = new Currency(code: "EGP", name: "Egyptian pound", symbol: "ج.م"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 27.00000000, longitude: 30.00000000)}
        , new Country { Id = 66, Name = "El Salvador", Iso3 = "SLV", Iso2 = "SV", NumericCode = "222", PhoneCode = "503", Capital = "San Salvador", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 13.83333333, longitude: -88.91666666)}
        , new Country { Id = 67, Name = "Equatorial Guinea", Iso3 = "GNQ", Iso2 = "GQ", NumericCode = "226", PhoneCode = "240", Capital = "Malabo", Currency = new Currency(code: "XAF", name: "Central African CFA franc", symbol: "FCFA"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 2.00000000, longitude: 10.00000000)}
        , new Country { Id = 68, Name = "Eritrea", Iso3 = "ERI", Iso2 = "ER", NumericCode = "232", PhoneCode = "291", Capital = "Asmara", Currency = new Currency(code: "ERN", name: "Eritrean nakfa", symbol: "Nfk"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: 15.00000000, longitude: 39.00000000)}
        , new Country { Id = 69, Name = "Estonia", Iso3 = "EST", Iso2 = "EE", NumericCode = "233", PhoneCode = "372", Capital = "Tallinn", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 59.00000000, longitude: 26.00000000)}
        , new Country { Id = 70, Name = "Ethiopia", Iso3 = "ETH", Iso2 = "ET", NumericCode = "231", PhoneCode = "251", Capital = "Addis Ababa", Currency = new Currency(code: "ETB", name: "Ethiopian birr", symbol: "Nkf"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: 8.00000000, longitude: 38.00000000)}
        , new Country { Id = 71, Name = "Falkland Islands", Iso3 = "FLK", Iso2 = "FK", NumericCode = "238", PhoneCode = "500", Capital = "Stanley", Currency = new Currency(code: "FKP", name: "Falkland Islands pound", symbol: "£"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -51.75000000, longitude: -59.00000000)}
        , new Country { Id = 72, Name = "Faroe Islands", Iso3 = "FRO", Iso2 = "FO", NumericCode = "234", PhoneCode = "298", Capital = "Torshavn", Currency = new Currency(code: "DKK", name: "Danish krone", symbol: "Kr."), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 62.00000000, longitude: -7.00000000)}
        , new Country { Id = 73, Name = "Fiji Islands", Iso3 = "FJI", Iso2 = "FJ", NumericCode = "242", PhoneCode = "679", Capital = "Suva", Currency = new Currency(code: "FJD", name: "Fijian dollar", symbol: "FJ$"), Region = new Region(name: "Oceania", subregion: "Melanesia"), GeoLocation = new GeoLocation(latitude: -18.00000000, longitude: 175.00000000)}
        , new Country { Id = 74, Name = "Finland", Iso3 = "FIN", Iso2 = "FI", NumericCode = "246", PhoneCode = "358", Capital = "Helsinki", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 64.00000000, longitude: 26.00000000)}
        , new Country { Id = 75, Name = "France", Iso3 = "FRA", Iso2 = "FR", NumericCode = "250", PhoneCode = "33", Capital = "Paris", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 46.00000000, longitude: 2.00000000)}
        , new Country { Id = 76, Name = "French Guiana", Iso3 = "GUF", Iso2 = "GF", NumericCode = "254", PhoneCode = "594", Capital = "Cayenne", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: 4.00000000, longitude: -53.00000000)}
        , new Country { Id = 77, Name = "French Polynesia", Iso3 = "PYF", Iso2 = "PF", NumericCode = "258", PhoneCode = "689", Capital = "Papeete", Currency = new Currency(code: "XPF", name: "CFP franc", symbol: "₣"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -15.00000000, longitude: -140.00000000)}
        , new Country { Id = 78, Name = "French Southern Territories", Iso3 = "ATF", Iso2 = "TF", NumericCode = "260", PhoneCode = "262", Capital = "Port-aux-Francais", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Africa", subregion: "Southern Africa"), GeoLocation = new GeoLocation(latitude: -49.25000000, longitude: 69.16700000)}
        , new Country { Id = 79, Name = "Gabon", Iso3 = "GAB", Iso2 = "GA", NumericCode = "266", PhoneCode = "241", Capital = "Libreville", Currency = new Currency(code: "XAF", name: "Central African CFA franc", symbol: "FCFA"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: -1.00000000, longitude: 11.75000000)}
        , new Country { Id = 80, Name = "Gambia The", Iso3 = "GMB", Iso2 = "GM", NumericCode = "270", PhoneCode = "220", Capital = "Banjul", Currency = new Currency(code: "GMD", name: "Gambian dalasi", symbol: "D"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 13.46666666, longitude: -16.56666666)}
        , new Country { Id = 81, Name = "Georgia", Iso3 = "GEO", Iso2 = "GE", NumericCode = "268", PhoneCode = "995", Capital = "Tbilisi", Currency = new Currency(code: "GEL", name: "Georgian lari", symbol: "ლ"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 42.00000000, longitude: 43.50000000)}
        , new Country { Id = 82, Name = "Germany", Iso3 = "DEU", Iso2 = "DE", NumericCode = "276", PhoneCode = "49", Capital = "Berlin", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 51.00000000, longitude: 9.00000000)}
        , new Country { Id = 83, Name = "Ghana", Iso3 = "GHA", Iso2 = "GH", NumericCode = "288", PhoneCode = "233", Capital = "Accra", Currency = new Currency(code: "GHS", name: "Ghanaian cedi", symbol: "GH₵"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 8.00000000, longitude: -2.00000000)}
        , new Country { Id = 84, Name = "Gibraltar", Iso3 = "GIB", Iso2 = "GI", NumericCode = "292", PhoneCode = "350", Capital = "Gibraltar", Currency = new Currency(code: "GIP", name: "Gibraltar pound", symbol: "£"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 36.13333333, longitude: -5.35000000)}
        , new Country { Id = 85, Name = "Greece", Iso3 = "GRC", Iso2 = "GR", NumericCode = "300", PhoneCode = "30", Capital = "Athens", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 39.00000000, longitude: 22.00000000)}
        , new Country { Id = 86, Name = "Greenland", Iso3 = "GRL", Iso2 = "GL", NumericCode = "304", PhoneCode = "299", Capital = "Nuuk", Currency = new Currency(code: "DKK", name: "Danish krone", symbol: "Kr."), Region = new Region(name: "Americas", subregion: "Northern America"), GeoLocation = new GeoLocation(latitude: 72.00000000, longitude: -40.00000000)}
        , new Country { Id = 87, Name = "Grenada", Iso3 = "GRD", Iso2 = "GD", NumericCode = "308", PhoneCode = "+1-473", Capital = "St. George's", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 12.11666666, longitude: -61.66666666)}
        , new Country { Id = 88, Name = "Guadeloupe", Iso3 = "GLP", Iso2 = "GP", NumericCode = "312", PhoneCode = "590", Capital = "Basse-Terre", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 16.25000000, longitude: -61.58333300)}
        , new Country { Id = 89, Name = "Guam", Iso3 = "GUM", Iso2 = "GU", NumericCode = "316", PhoneCode = "+1-671", Capital = "Hagatna", Currency = new Currency(code: "USD", name: "US Dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: 13.46666666, longitude: 144.78333333)}
        , new Country { Id = 90, Name = "Guatemala", Iso3 = "GTM", Iso2 = "GT", NumericCode = "320", PhoneCode = "502", Capital = "Guatemala City", Currency = new Currency(code: "GTQ", name: "Guatemalan quetzal", symbol: "Q"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 15.50000000, longitude: -90.25000000)}
        , new Country { Id = 91, Name = "Guernsey and Alderney", Iso3 = "GGY", Iso2 = "GG", NumericCode = "831", PhoneCode = "+44-1481", Capital = "St Peter Port", Currency = new Currency(code: "GBP", name: "British pound", symbol: "£"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 49.46666666, longitude: -2.58333333)}
        , new Country { Id = 92, Name = "Guinea", Iso3 = "GIN", Iso2 = "GN", NumericCode = "324", PhoneCode = "224", Capital = "Conakry", Currency = new Currency(code: "GNF", name: "Guinean franc", symbol: "FG"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 11.00000000, longitude: -10.00000000)}
        , new Country { Id = 93, Name = "Guinea-Bissau", Iso3 = "GNB", Iso2 = "GW", NumericCode = "624", PhoneCode = "245", Capital = "Bissau", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 12.00000000, longitude: -15.00000000)}
        , new Country { Id = 94, Name = "Guyana", Iso3 = "GUY", Iso2 = "GY", NumericCode = "328", PhoneCode = "592", Capital = "Georgetown", Currency = new Currency(code: "GYD", name: "Guyanese dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: 5.00000000, longitude: -59.00000000)}
        , new Country { Id = 95, Name = "Haiti", Iso3 = "HTI", Iso2 = "HT", NumericCode = "332", PhoneCode = "509", Capital = "Port-au-Prince", Currency = new Currency(code: "HTG", name: "Haitian gourde", symbol: "G"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 19.00000000, longitude: -72.41666666)}
        , new Country { Id = 96, Name = "Heard Island and McDonald Islands", Iso3 = "HMD", Iso2 = "HM", NumericCode = "334", PhoneCode = "672", Capital = "", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "", subregion: ""), GeoLocation = new GeoLocation(latitude: -53.10000000, longitude: 72.51666666)}
        , new Country { Id = 97, Name = "Honduras", Iso3 = "HND", Iso2 = "HN", NumericCode = "340", PhoneCode = "504", Capital = "Tegucigalpa", Currency = new Currency(code: "HNL", name: "Honduran lempira", symbol: "L"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 15.00000000, longitude: -86.50000000)}
        , new Country { Id = 98, Name = "Hong Kong S.A.R.", Iso3 = "HKG", Iso2 = "HK", NumericCode = "344", PhoneCode = "852", Capital = "Hong Kong", Currency = new Currency(code: "HKD", name: "Hong Kong dollar", symbol: "$"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 22.25000000, longitude: 114.16666666)}
        , new Country { Id = 99, Name = "Hungary", Iso3 = "HUN", Iso2 = "HU", NumericCode = "348", PhoneCode = "36", Capital = "Budapest", Currency = new Currency(code: "HUF", name: "Hungarian forint", symbol: "Ft"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 47.00000000, longitude: 20.00000000)}
        , new Country { Id = 100, Name = "Iceland", Iso3 = "ISL", Iso2 = "IS", NumericCode = "352", PhoneCode = "354", Capital = "Reykjavik", Currency = new Currency(code: "ISK", name: "Icelandic króna", symbol: "kr"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 65.00000000, longitude: -18.00000000)}
        , new Country { Id = 101, Name = "India", Iso3 = "IND", Iso2 = "IN", NumericCode = "356", PhoneCode = "91", Capital = "New Delhi", Currency = new Currency(code: "INR", name: "Indian rupee", symbol: "₹"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 20.00000000, longitude: 77.00000000)}
        , new Country { Id = 102, Name = "Indonesia", Iso3 = "IDN", Iso2 = "ID", NumericCode = "360", PhoneCode = "62", Capital = "Jakarta", Currency = new Currency(code: "IDR", name: "Indonesian rupiah", symbol: "Rp"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: -5.00000000, longitude: 120.00000000)}
        , new Country { Id = 103, Name = "Iran", Iso3 = "IRN", Iso2 = "IR", NumericCode = "364", PhoneCode = "98", Capital = "Tehran", Currency = new Currency(code: "IRR", name: "Iranian rial", symbol: "﷼"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 32.00000000, longitude: 53.00000000)}
        , new Country { Id = 104, Name = "Iraq", Iso3 = "IRQ", Iso2 = "IQ", NumericCode = "368", PhoneCode = "964", Capital = "Baghdad", Currency = new Currency(code: "IQD", name: "Iraqi dinar", symbol: "د.ع"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 33.00000000, longitude: 44.00000000)}
        , new Country { Id = 105, Name = "Ireland", Iso3 = "IRL", Iso2 = "IE", NumericCode = "372", PhoneCode = "353", Capital = "Dublin", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 53.00000000, longitude: -8.00000000)}
        , new Country { Id = 106, Name = "Israel", Iso3 = "ISR", Iso2 = "IL", NumericCode = "376", PhoneCode = "972", Capital = "Jerusalem", Currency = new Currency(code: "ILS", name: "Israeli new shekel", symbol: "₪"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 31.50000000, longitude: 34.75000000)}
        , new Country { Id = 107, Name = "Italy", Iso3 = "ITA", Iso2 = "IT", NumericCode = "380", PhoneCode = "39", Capital = "Rome", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 42.83333333, longitude: 12.83333333)}
        , new Country { Id = 108, Name = "Jamaica", Iso3 = "JAM", Iso2 = "JM", NumericCode = "388", PhoneCode = "+1-876", Capital = "Kingston", Currency = new Currency(code: "JMD", name: "Jamaican dollar", symbol: "J$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.25000000, longitude: -77.50000000)}
        , new Country { Id = 109, Name = "Japan", Iso3 = "JPN", Iso2 = "JP", NumericCode = "392", PhoneCode = "81", Capital = "Tokyo", Currency = new Currency(code: "JPY", name: "Japanese yen", symbol: "¥"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 36.00000000, longitude: 138.00000000)}
        , new Country { Id = 110, Name = "Jersey", Iso3 = "JEY", Iso2 = "JE", NumericCode = "832", PhoneCode = "+44-1534", Capital = "Saint Helier", Currency = new Currency(code: "GBP", name: "British pound", symbol: "£"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 49.25000000, longitude: -2.16666666)}
        , new Country { Id = 111, Name = "Jordan", Iso3 = "JOR", Iso2 = "JO", NumericCode = "400", PhoneCode = "962", Capital = "Amman", Currency = new Currency(code: "JOD", name: "Jordanian dinar", symbol: "ا.د"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 31.00000000, longitude: 36.00000000)}
        , new Country { Id = 112, Name = "Kazakhstan", Iso3 = "KAZ", Iso2 = "KZ", NumericCode = "398", PhoneCode = "7", Capital = "Astana", Currency = new Currency(code: "KZT", name: "Kazakhstani tenge", symbol: "лв"), Region = new Region(name: "Asia", subregion: "Central Asia"), GeoLocation = new GeoLocation(latitude: 48.00000000, longitude: 68.00000000)}
        , new Country { Id = 113, Name = "Kenya", Iso3 = "KEN", Iso2 = "KE", NumericCode = "404", PhoneCode = "254", Capital = "Nairobi", Currency = new Currency(code: "KES", name: "Kenyan shilling", symbol: "KSh"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: 1.00000000, longitude: 38.00000000)}
        , new Country { Id = 114, Name = "Kiribati", Iso3 = "KIR", Iso2 = "KI", NumericCode = "296", PhoneCode = "686", Capital = "Tarawa", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: 1.41666666, longitude: 173.00000000)}
        , new Country { Id = 248, Name = "Kosovo", Iso3 = "XKX", Iso2 = "XK", NumericCode = "926", PhoneCode = "383", Capital = "Pristina", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 42.56129090, longitude: 20.34030350)}
        , new Country { Id = 117, Name = "Kuwait", Iso3 = "KWT", Iso2 = "KW", NumericCode = "414", PhoneCode = "965", Capital = "Kuwait City", Currency = new Currency(code: "KWD", name: "Kuwaiti dinar", symbol: "ك.د"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 29.50000000, longitude: 45.75000000)}
        , new Country { Id = 118, Name = "Kyrgyzstan", Iso3 = "KGZ", Iso2 = "KG", NumericCode = "417", PhoneCode = "996", Capital = "Bishkek", Currency = new Currency(code: "KGS", name: "Kyrgyzstani som", symbol: "лв"), Region = new Region(name: "Asia", subregion: "Central Asia"), GeoLocation = new GeoLocation(latitude: 41.00000000, longitude: 75.00000000)}
        , new Country { Id = 119, Name = "Laos", Iso3 = "LAO", Iso2 = "LA", NumericCode = "418", PhoneCode = "856", Capital = "Vientiane", Currency = new Currency(code: "LAK", name: "Lao kip", symbol: "₭"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 18.00000000, longitude: 105.00000000)}
        , new Country { Id = 120, Name = "Latvia", Iso3 = "LVA", Iso2 = "LV", NumericCode = "428", PhoneCode = "371", Capital = "Riga", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 57.00000000, longitude: 25.00000000)}
        , new Country { Id = 121, Name = "Lebanon", Iso3 = "LBN", Iso2 = "LB", NumericCode = "422", PhoneCode = "961", Capital = "Beirut", Currency = new Currency(code: "LBP", name: "Lebanese pound", symbol: "£"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 33.83333333, longitude: 35.83333333)}
        , new Country { Id = 122, Name = "Lesotho", Iso3 = "LSO", Iso2 = "LS", NumericCode = "426", PhoneCode = "266", Capital = "Maseru", Currency = new Currency(code: "LSL", name: "Lesotho loti", symbol: "L"), Region = new Region(name: "Africa", subregion: "Southern Africa"), GeoLocation = new GeoLocation(latitude: -29.50000000, longitude: 28.50000000)}
        , new Country { Id = 123, Name = "Liberia", Iso3 = "LBR", Iso2 = "LR", NumericCode = "430", PhoneCode = "231", Capital = "Monrovia", Currency = new Currency(code: "LRD", name: "Liberian dollar", symbol: "$"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 6.50000000, longitude: -9.50000000)}
        , new Country { Id = 124, Name = "Libya", Iso3 = "LBY", Iso2 = "LY", NumericCode = "434", PhoneCode = "218", Capital = "Tripolis", Currency = new Currency(code: "LYD", name: "Libyan dinar", symbol: "د.ل"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 25.00000000, longitude: 17.00000000)}
        , new Country { Id = 125, Name = "Liechtenstein", Iso3 = "LIE", Iso2 = "LI", NumericCode = "438", PhoneCode = "423", Capital = "Vaduz", Currency = new Currency(code: "CHF", name: "Swiss franc", symbol: "CHf"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 47.26666666, longitude: 9.53333333)}
        , new Country { Id = 126, Name = "Lithuania", Iso3 = "LTU", Iso2 = "LT", NumericCode = "440", PhoneCode = "370", Capital = "Vilnius", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 56.00000000, longitude: 24.00000000)}
        , new Country { Id = 127, Name = "Luxembourg", Iso3 = "LUX", Iso2 = "LU", NumericCode = "442", PhoneCode = "352", Capital = "Luxembourg", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 49.75000000, longitude: 6.16666666)}
        , new Country { Id = 128, Name = "Macau S.A.R.", Iso3 = "MAC", Iso2 = "MO", NumericCode = "446", PhoneCode = "853", Capital = "Macao", Currency = new Currency(code: "MOP", name: "Macanese pataca", symbol: "$"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 22.16666666, longitude: 113.55000000)}
        , new Country { Id = 130, Name = "Madagascar", Iso3 = "MDG", Iso2 = "MG", NumericCode = "450", PhoneCode = "261", Capital = "Antananarivo", Currency = new Currency(code: "MGA", name: "Malagasy ariary", symbol: "Ar"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -20.00000000, longitude: 47.00000000)}
        , new Country { Id = 131, Name = "Malawi", Iso3 = "MWI", Iso2 = "MW", NumericCode = "454", PhoneCode = "265", Capital = "Lilongwe", Currency = new Currency(code: "MWK", name: "Malawian kwacha", symbol: "MK"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -13.50000000, longitude: 34.00000000)}
        , new Country { Id = 132, Name = "Malaysia", Iso3 = "MYS", Iso2 = "MY", NumericCode = "458", PhoneCode = "60", Capital = "Kuala Lumpur", Currency = new Currency(code: "MYR", name: "Malaysian ringgit", symbol: "RM"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 2.50000000, longitude: 112.50000000)}
        , new Country { Id = 133, Name = "Maldives", Iso3 = "MDV", Iso2 = "MV", NumericCode = "462", PhoneCode = "960", Capital = "Male", Currency = new Currency(code: "MVR", name: "Maldivian rufiyaa", symbol: "Rf"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 3.25000000, longitude: 73.00000000)}
        , new Country { Id = 134, Name = "Mali", Iso3 = "MLI", Iso2 = "ML", NumericCode = "466", PhoneCode = "223", Capital = "Bamako", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 17.00000000, longitude: -4.00000000)}
        , new Country { Id = 135, Name = "Malta", Iso3 = "MLT", Iso2 = "MT", NumericCode = "470", PhoneCode = "356", Capital = "Valletta", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 35.83333333, longitude: 14.58333333)}
        , new Country { Id = 136, Name = "Man (Isle of)", Iso3 = "IMN", Iso2 = "IM", NumericCode = "833", PhoneCode = "+44-1624", Capital = "Douglas, Isle of Man", Currency = new Currency(code: "GBP", name: "British pound", symbol: "£"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 54.25000000, longitude: -4.50000000)}
        , new Country { Id = 137, Name = "Marshall Islands", Iso3 = "MHL", Iso2 = "MH", NumericCode = "584", PhoneCode = "692", Capital = "Majuro", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: 9.00000000, longitude: 168.00000000)}
        , new Country { Id = 138, Name = "Martinique", Iso3 = "MTQ", Iso2 = "MQ", NumericCode = "474", PhoneCode = "596", Capital = "Fort-de-France", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 14.66666700, longitude: -61.00000000)}
        , new Country { Id = 139, Name = "Mauritania", Iso3 = "MRT", Iso2 = "MR", NumericCode = "478", PhoneCode = "222", Capital = "Nouakchott", Currency = new Currency(code: "MRO", name: "Mauritanian ouguiya", symbol: "MRU"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 20.00000000, longitude: -12.00000000)}
        , new Country { Id = 140, Name = "Mauritius", Iso3 = "MUS", Iso2 = "MU", NumericCode = "480", PhoneCode = "230", Capital = "Port Louis", Currency = new Currency(code: "MUR", name: "Mauritian rupee", symbol: "₨"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -20.28333333, longitude: 57.55000000)}
        , new Country { Id = 141, Name = "Mayotte", Iso3 = "MYT", Iso2 = "YT", NumericCode = "175", PhoneCode = "262", Capital = "Mamoudzou", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -12.83333333, longitude: 45.16666666)}
        , new Country { Id = 142, Name = "Mexico", Iso3 = "MEX", Iso2 = "MX", NumericCode = "484", PhoneCode = "52", Capital = "Ciudad de México", Currency = new Currency(code: "MXN", name: "Mexican peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 23.00000000, longitude: -102.00000000)}
        , new Country { Id = 143, Name = "Micronesia", Iso3 = "FSM", Iso2 = "FM", NumericCode = "583", PhoneCode = "691", Capital = "Palikir", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: 6.91666666, longitude: 158.25000000)}
        , new Country { Id = 144, Name = "Moldova", Iso3 = "MDA", Iso2 = "MD", NumericCode = "498", PhoneCode = "373", Capital = "Chisinau", Currency = new Currency(code: "MDL", name: "Moldovan leu", symbol: "L"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 47.00000000, longitude: 29.00000000)}
        , new Country { Id = 145, Name = "Monaco", Iso3 = "MCO", Iso2 = "MC", NumericCode = "492", PhoneCode = "377", Capital = "Monaco", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 43.73333333, longitude: 7.40000000)}
        , new Country { Id = 146, Name = "Mongolia", Iso3 = "MNG", Iso2 = "MN", NumericCode = "496", PhoneCode = "976", Capital = "Ulan Bator", Currency = new Currency(code: "MNT", name: "Mongolian tögrög", symbol: "₮"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 46.00000000, longitude: 105.00000000)}
        , new Country { Id = 147, Name = "Montenegro", Iso3 = "MNE", Iso2 = "ME", NumericCode = "499", PhoneCode = "382", Capital = "Podgorica", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 42.50000000, longitude: 19.30000000)}
        , new Country { Id = 148, Name = "Montserrat", Iso3 = "MSR", Iso2 = "MS", NumericCode = "500", PhoneCode = "+1-664", Capital = "Plymouth", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 16.75000000, longitude: -62.20000000)}
        , new Country { Id = 149, Name = "Morocco", Iso3 = "MAR", Iso2 = "MA", NumericCode = "504", PhoneCode = "212", Capital = "Rabat", Currency = new Currency(code: "MAD", name: "Moroccan dirham", symbol: "DH"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 32.00000000, longitude: -5.00000000)}
        , new Country { Id = 150, Name = "Mozambique", Iso3 = "MOZ", Iso2 = "MZ", NumericCode = "508", PhoneCode = "258", Capital = "Maputo", Currency = new Currency(code: "MZN", name: "Mozambican metical", symbol: "MT"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -18.25000000, longitude: 35.00000000)}
        , new Country { Id = 151, Name = "Myanmar", Iso3 = "MMR", Iso2 = "MM", NumericCode = "104", PhoneCode = "95", Capital = "Nay Pyi Taw", Currency = new Currency(code: "MMK", name: "Burmese kyat", symbol: "K"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 22.00000000, longitude: 98.00000000)}
        , new Country { Id = 152, Name = "Namibia", Iso3 = "NAM", Iso2 = "NA", NumericCode = "516", PhoneCode = "264", Capital = "Windhoek", Currency = new Currency(code: "NAD", name: "Namibian dollar", symbol: "$"), Region = new Region(name: "Africa", subregion: "Southern Africa"), GeoLocation = new GeoLocation(latitude: -22.00000000, longitude: 17.00000000)}
        , new Country { Id = 153, Name = "Nauru", Iso3 = "NRU", Iso2 = "NR", NumericCode = "520", PhoneCode = "674", Capital = "Yaren", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: -0.53333333, longitude: 166.91666666)}
        , new Country { Id = 154, Name = "Nepal", Iso3 = "NPL", Iso2 = "NP", NumericCode = "524", PhoneCode = "977", Capital = "Kathmandu", Currency = new Currency(code: "NPR", name: "Nepalese rupee", symbol: "₨"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 28.00000000, longitude: 84.00000000)}
        , new Country { Id = 156, Name = "Netherlands", Iso3 = "NLD", Iso2 = "NL", NumericCode = "528", PhoneCode = "31", Capital = "Amsterdam", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 52.50000000, longitude: 5.75000000)}
        , new Country { Id = 157, Name = "New Caledonia", Iso3 = "NCL", Iso2 = "NC", NumericCode = "540", PhoneCode = "687", Capital = "Noumea", Currency = new Currency(code: "XPF", name: "CFP franc", symbol: "₣"), Region = new Region(name: "Oceania", subregion: "Melanesia"), GeoLocation = new GeoLocation(latitude: -21.50000000, longitude: 165.50000000)}
        , new Country { Id = 158, Name = "New Zealand", Iso3 = "NZL", Iso2 = "NZ", NumericCode = "554", PhoneCode = "64", Capital = "Wellington", Currency = new Currency(code: "NZD", name: "New Zealand dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Australia and New Zealand"), GeoLocation = new GeoLocation(latitude: -41.00000000, longitude: 174.00000000)}
        , new Country { Id = 159, Name = "Nicaragua", Iso3 = "NIC", Iso2 = "NI", NumericCode = "558", PhoneCode = "505", Capital = "Managua", Currency = new Currency(code: "NIO", name: "Nicaraguan córdoba", symbol: "C$"), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 13.00000000, longitude: -85.00000000)}
        , new Country { Id = 160, Name = "Niger", Iso3 = "NER", Iso2 = "NE", NumericCode = "562", PhoneCode = "227", Capital = "Niamey", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 16.00000000, longitude: 8.00000000)}
        , new Country { Id = 161, Name = "Nigeria", Iso3 = "NGA", Iso2 = "NG", NumericCode = "566", PhoneCode = "234", Capital = "Abuja", Currency = new Currency(code: "NGN", name: "Nigerian naira", symbol: "₦"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 10.00000000, longitude: 8.00000000)}
        , new Country { Id = 162, Name = "Niue", Iso3 = "NIU", Iso2 = "NU", NumericCode = "570", PhoneCode = "683", Capital = "Alofi", Currency = new Currency(code: "NZD", name: "New Zealand dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -19.03333333, longitude: -169.86666666)}
        , new Country { Id = 163, Name = "Norfolk Island", Iso3 = "NFK", Iso2 = "NF", NumericCode = "574", PhoneCode = "672", Capital = "Kingston", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Australia and New Zealand"), GeoLocation = new GeoLocation(latitude: -29.03333333, longitude: 167.95000000)}
        , new Country { Id = 115, Name = "North Korea", Iso3 = "PRK", Iso2 = "KP", NumericCode = "408", PhoneCode = "850", Capital = "Pyongyang", Currency = new Currency(code: "KPW", name: "North Korean Won", symbol: "₩"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 40.00000000, longitude: 127.00000000)}
        , new Country { Id = 129, Name = "North Macedonia", Iso3 = "MKD", Iso2 = "MK", NumericCode = "807", PhoneCode = "389", Capital = "Skopje", Currency = new Currency(code: "MKD", name: "Denar", symbol: "ден"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 41.83333333, longitude: 22.00000000)}
        , new Country { Id = 164, Name = "Northern Mariana Islands", Iso3 = "MNP", Iso2 = "MP", NumericCode = "580", PhoneCode = "+1-670", Capital = "Saipan", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: 15.20000000, longitude: 145.75000000)}
        , new Country { Id = 165, Name = "Norway", Iso3 = "NOR", Iso2 = "NO", NumericCode = "578", PhoneCode = "47", Capital = "Oslo", Currency = new Currency(code: "NOK", name: "Norwegian krone", symbol: "kr"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 62.00000000, longitude: 10.00000000)}
        , new Country { Id = 166, Name = "Oman", Iso3 = "OMN", Iso2 = "OM", NumericCode = "512", PhoneCode = "968", Capital = "Muscat", Currency = new Currency(code: "OMR", name: "Omani rial", symbol: ".ع.ر"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 21.00000000, longitude: 57.00000000)}
        , new Country { Id = 167, Name = "Pakistan", Iso3 = "PAK", Iso2 = "PK", NumericCode = "586", PhoneCode = "92", Capital = "Islamabad", Currency = new Currency(code: "PKR", name: "Pakistani rupee", symbol: "₨"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 30.00000000, longitude: 70.00000000)}
        , new Country { Id = 168, Name = "Palau", Iso3 = "PLW", Iso2 = "PW", NumericCode = "585", PhoneCode = "680", Capital = "Melekeok", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Micronesia"), GeoLocation = new GeoLocation(latitude: 7.50000000, longitude: 134.50000000)}
        , new Country { Id = 169, Name = "Palestinian Territory Occupied", Iso3 = "PSE", Iso2 = "PS", NumericCode = "275", PhoneCode = "970", Capital = "East Jerusalem", Currency = new Currency(code: "ILS", name: "Israeli new shekel", symbol: "₪"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 31.90000000, longitude: 35.20000000)}
        , new Country { Id = 170, Name = "Panama", Iso3 = "PAN", Iso2 = "PA", NumericCode = "591", PhoneCode = "507", Capital = "Panama City", Currency = new Currency(code: "PAB", name: "Panamanian balboa", symbol: "B/."), Region = new Region(name: "Americas", subregion: "Central America"), GeoLocation = new GeoLocation(latitude: 9.00000000, longitude: -80.00000000)}
        , new Country { Id = 171, Name = "Papua new Guinea", Iso3 = "PNG", Iso2 = "PG", NumericCode = "598", PhoneCode = "675", Capital = "Port Moresby", Currency = new Currency(code: "PGK", name: "Papua New Guinean kina", symbol: "K"), Region = new Region(name: "Oceania", subregion: "Melanesia"), GeoLocation = new GeoLocation(latitude: -6.00000000, longitude: 147.00000000)}
        , new Country { Id = 172, Name = "Paraguay", Iso3 = "PRY", Iso2 = "PY", NumericCode = "600", PhoneCode = "595", Capital = "Asuncion", Currency = new Currency(code: "PYG", name: "Paraguayan guarani", symbol: "₲"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -23.00000000, longitude: -58.00000000)}
        , new Country { Id = 173, Name = "Peru", Iso3 = "PER", Iso2 = "PE", NumericCode = "604", PhoneCode = "51", Capital = "Lima", Currency = new Currency(code: "PEN", name: "Peruvian sol", symbol: "S/."), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -10.00000000, longitude: -76.00000000)}
        , new Country { Id = 174, Name = "Philippines", Iso3 = "PHL", Iso2 = "PH", NumericCode = "608", PhoneCode = "63", Capital = "Manila", Currency = new Currency(code: "PHP", name: "Philippine peso", symbol: "₱"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 13.00000000, longitude: 122.00000000)}
        , new Country { Id = 175, Name = "Pitcairn Island", Iso3 = "PCN", Iso2 = "PN", NumericCode = "612", PhoneCode = "870", Capital = "Adamstown", Currency = new Currency(code: "NZD", name: "New Zealand dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -25.06666666, longitude: -130.10000000)}
        , new Country { Id = 176, Name = "Poland", Iso3 = "POL", Iso2 = "PL", NumericCode = "616", PhoneCode = "48", Capital = "Warsaw", Currency = new Currency(code: "PLN", name: "Polish złoty", symbol: "zł"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 52.00000000, longitude: 20.00000000)}
        , new Country { Id = 177, Name = "Portugal", Iso3 = "PRT", Iso2 = "PT", NumericCode = "620", PhoneCode = "351", Capital = "Lisbon", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 39.50000000, longitude: -8.00000000)}
        , new Country { Id = 178, Name = "Puerto Rico", Iso3 = "PRI", Iso2 = "PR", NumericCode = "630", PhoneCode = "+1-787 and 1-939", Capital = "San Juan", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.25000000, longitude: -66.50000000)}
        , new Country { Id = 179, Name = "Qatar", Iso3 = "QAT", Iso2 = "QA", NumericCode = "634", PhoneCode = "974", Capital = "Doha", Currency = new Currency(code: "QAR", name: "Qatari riyal", symbol: "ق.ر"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 25.50000000, longitude: 51.25000000)}
        , new Country { Id = 180, Name = "Reunion", Iso3 = "REU", Iso2 = "RE", NumericCode = "638", PhoneCode = "262", Capital = "Saint-Denis", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -21.15000000, longitude: 55.50000000)}
        , new Country { Id = 181, Name = "Romania", Iso3 = "ROU", Iso2 = "RO", NumericCode = "642", PhoneCode = "40", Capital = "Bucharest", Currency = new Currency(code: "RON", name: "Romanian leu", symbol: "lei"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 46.00000000, longitude: 25.00000000)}
        , new Country { Id = 182, Name = "Russia", Iso3 = "RUS", Iso2 = "RU", NumericCode = "643", PhoneCode = "7", Capital = "Moscow", Currency = new Currency(code: "RUB", name: "Russian ruble", symbol: "₽"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 60.00000000, longitude: 100.00000000)}
        , new Country { Id = 183, Name = "Rwanda", Iso3 = "RWA", Iso2 = "RW", NumericCode = "646", PhoneCode = "250", Capital = "Kigali", Currency = new Currency(code: "RWF", name: "Rwandan franc", symbol: "FRw"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -2.00000000, longitude: 30.00000000)}
        , new Country { Id = 184, Name = "Saint Helena", Iso3 = "SHN", Iso2 = "SH", NumericCode = "654", PhoneCode = "290", Capital = "Jamestown", Currency = new Currency(code: "SHP", name: "Saint Helena pound", symbol: "£"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: -15.95000000, longitude: -5.70000000)}
        , new Country { Id = 185, Name = "Saint Kitts And Nevis", Iso3 = "KNA", Iso2 = "KN", NumericCode = "659", PhoneCode = "+1-869", Capital = "Basseterre", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 17.33333333, longitude: -62.75000000)}
        , new Country { Id = 186, Name = "Saint Lucia", Iso3 = "LCA", Iso2 = "LC", NumericCode = "662", PhoneCode = "+1-758", Capital = "Castries", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 13.88333333, longitude: -60.96666666)}
        , new Country { Id = 187, Name = "Saint Pierre and Miquelon", Iso3 = "SPM", Iso2 = "PM", NumericCode = "666", PhoneCode = "508", Capital = "Saint-Pierre", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Americas", subregion: "Northern America"), GeoLocation = new GeoLocation(latitude: 46.83333333, longitude: -56.33333333)}
        , new Country { Id = 188, Name = "Saint Vincent And The Grenadines", Iso3 = "VCT", Iso2 = "VC", NumericCode = "670", PhoneCode = "+1-784", Capital = "Kingstown", Currency = new Currency(code: "XCD", name: "Eastern Caribbean dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 13.25000000, longitude: -61.20000000)}
        , new Country { Id = 189, Name = "Saint-Barthelemy", Iso3 = "BLM", Iso2 = "BL", NumericCode = "652", PhoneCode = "590", Capital = "Gustavia", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.50000000, longitude: -63.41666666)}
        , new Country { Id = 190, Name = "Saint-Martin (French part)", Iso3 = "MAF", Iso2 = "MF", NumericCode = "663", PhoneCode = "590", Capital = "Marigot", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.08333333, longitude: -63.95000000)}
        , new Country { Id = 191, Name = "Samoa", Iso3 = "WSM", Iso2 = "WS", NumericCode = "882", PhoneCode = "685", Capital = "Apia", Currency = new Currency(code: "WST", name: "Samoan tālā", symbol: "SAT"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -13.58333333, longitude: -172.33333333)}
        , new Country { Id = 192, Name = "San Marino", Iso3 = "SMR", Iso2 = "SM", NumericCode = "674", PhoneCode = "378", Capital = "San Marino", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 43.76666666, longitude: 12.41666666)}
        , new Country { Id = 193, Name = "Sao Tome and Principe", Iso3 = "STP", Iso2 = "ST", NumericCode = "678", PhoneCode = "239", Capital = "Sao Tome", Currency = new Currency(code: "STD", name: "Dobra", symbol: "Db"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 1.00000000, longitude: 7.00000000)}
        , new Country { Id = 194, Name = "Saudi Arabia", Iso3 = "SAU", Iso2 = "SA", NumericCode = "682", PhoneCode = "966", Capital = "Riyadh", Currency = new Currency(code: "SAR", name: "Saudi riyal", symbol: "﷼"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 25.00000000, longitude: 45.00000000)}
        , new Country { Id = 195, Name = "Senegal", Iso3 = "SEN", Iso2 = "SN", NumericCode = "686", PhoneCode = "221", Capital = "Dakar", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 14.00000000, longitude: -14.00000000)}
        , new Country { Id = 196, Name = "Serbia", Iso3 = "SRB", Iso2 = "RS", NumericCode = "688", PhoneCode = "381", Capital = "Belgrade", Currency = new Currency(code: "RSD", name: "Serbian dinar", symbol: "din"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 44.00000000, longitude: 21.00000000)}
        , new Country { Id = 197, Name = "Seychelles", Iso3 = "SYC", Iso2 = "SC", NumericCode = "690", PhoneCode = "248", Capital = "Victoria", Currency = new Currency(code: "SCR", name: "Seychellois rupee", symbol: "SRe"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -4.58333333, longitude: 55.66666666)}
        , new Country { Id = 198, Name = "Sierra Leone", Iso3 = "SLE", Iso2 = "SL", NumericCode = "694", PhoneCode = "232", Capital = "Freetown", Currency = new Currency(code: "SLL", name: "Sierra Leonean leone", symbol: "Le"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 8.50000000, longitude: -11.50000000)}
        , new Country { Id = 199, Name = "Singapore", Iso3 = "SGP", Iso2 = "SG", NumericCode = "702", PhoneCode = "65", Capital = "Singapur", Currency = new Currency(code: "SGD", name: "Singapore dollar", symbol: "$"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 1.36666666, longitude: 103.80000000)}
        , new Country { Id = 250, Name = "Sint Maarten (Dutch part)", Iso3 = "SXM", Iso2 = "SX", NumericCode = "534", PhoneCode = "1721", Capital = "Philipsburg", Currency = new Currency(code: "ANG", name: "Netherlands Antillean guilder", symbol: "ƒ"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.03333300, longitude: -63.05000000)}
        , new Country { Id = 200, Name = "Slovakia", Iso3 = "SVK", Iso2 = "SK", NumericCode = "703", PhoneCode = "421", Capital = "Bratislava", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 48.66666666, longitude: 19.50000000)}
        , new Country { Id = 201, Name = "Slovenia", Iso3 = "SVN", Iso2 = "SI", NumericCode = "705", PhoneCode = "386", Capital = "Ljubljana", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 46.11666666, longitude: 14.81666666)}
        , new Country { Id = 202, Name = "Solomon Islands", Iso3 = "SLB", Iso2 = "SB", NumericCode = "090", PhoneCode = "677", Capital = "Honiara", Currency = new Currency(code: "SBD", name: "Solomon Islands dollar", symbol: "Si$"), Region = new Region(name: "Oceania", subregion: "Melanesia"), GeoLocation = new GeoLocation(latitude: -8.00000000, longitude: 159.00000000)}
        , new Country { Id = 203, Name = "Somalia", Iso3 = "SOM", Iso2 = "SO", NumericCode = "706", PhoneCode = "252", Capital = "Mogadishu", Currency = new Currency(code: "SOS", name: "Somali shilling", symbol: "Sh.so."), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: 10.00000000, longitude: 49.00000000)}
        , new Country { Id = 204, Name = "South Africa", Iso3 = "ZAF", Iso2 = "ZA", NumericCode = "710", PhoneCode = "27", Capital = "Pretoria", Currency = new Currency(code: "ZAR", name: "South African rand", symbol: "R"), Region = new Region(name: "Africa", subregion: "Southern Africa"), GeoLocation = new GeoLocation(latitude: -29.00000000, longitude: 24.00000000)}
        , new Country { Id = 205, Name = "South Georgia", Iso3 = "SGS", Iso2 = "GS", NumericCode = "239", PhoneCode = "500", Capital = "Grytviken", Currency = new Currency(code: "GBP", name: "British pound", symbol: "£"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -54.50000000, longitude: -37.00000000)}
        , new Country { Id = 116, Name = "South Korea", Iso3 = "KOR", Iso2 = "KR", NumericCode = "410", PhoneCode = "82", Capital = "Seoul", Currency = new Currency(code: "KRW", name: "Won", symbol: "₩"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 37.00000000, longitude: 127.50000000)}
        , new Country { Id = 206, Name = "South Sudan", Iso3 = "SSD", Iso2 = "SS", NumericCode = "728", PhoneCode = "211", Capital = "Juba", Currency = new Currency(code: "SSP", name: "South Sudanese pound", symbol: "£"), Region = new Region(name: "Africa", subregion: "Middle Africa"), GeoLocation = new GeoLocation(latitude: 7.00000000, longitude: 30.00000000)}
        , new Country { Id = 207, Name = "Spain", Iso3 = "ESP", Iso2 = "ES", NumericCode = "724", PhoneCode = "34", Capital = "Madrid", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 40.00000000, longitude: -4.00000000)}
        , new Country { Id = 208, Name = "Sri Lanka", Iso3 = "LKA", Iso2 = "LK", NumericCode = "144", PhoneCode = "94", Capital = "Colombo", Currency = new Currency(code: "LKR", name: "Sri Lankan rupee", symbol: "Rs"), Region = new Region(name: "Asia", subregion: "Southern Asia"), GeoLocation = new GeoLocation(latitude: 7.00000000, longitude: 81.00000000)}
        , new Country { Id = 209, Name = "Sudan", Iso3 = "SDN", Iso2 = "SD", NumericCode = "729", PhoneCode = "249", Capital = "Khartoum", Currency = new Currency(code: "SDG", name: "Sudanese pound", symbol: ".س.ج"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 15.00000000, longitude: 30.00000000)}
        , new Country { Id = 210, Name = "Suriname", Iso3 = "SUR", Iso2 = "SR", NumericCode = "740", PhoneCode = "597", Capital = "Paramaribo", Currency = new Currency(code: "SRD", name: "Surinamese dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: 4.00000000, longitude: -56.00000000)}
        , new Country { Id = 211, Name = "Svalbard And Jan Mayen Islands", Iso3 = "SJM", Iso2 = "SJ", NumericCode = "744", PhoneCode = "47", Capital = "Longyearbyen", Currency = new Currency(code: "NOK", name: "Norwegian Krone", symbol: "kr"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 78.00000000, longitude: 20.00000000)}
        , new Country { Id = 212, Name = "Swaziland", Iso3 = "SWZ", Iso2 = "SZ", NumericCode = "748", PhoneCode = "268", Capital = "Mbabane", Currency = new Currency(code: "SZL", name: "Lilangeni", symbol: "E"), Region = new Region(name: "Africa", subregion: "Southern Africa"), GeoLocation = new GeoLocation(latitude: -26.50000000, longitude: 31.50000000)}
        , new Country { Id = 213, Name = "Sweden", Iso3 = "SWE", Iso2 = "SE", NumericCode = "752", PhoneCode = "46", Capital = "Stockholm", Currency = new Currency(code: "SEK", name: "Swedish krona", symbol: "kr"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 62.00000000, longitude: 15.00000000)}
        , new Country { Id = 214, Name = "Switzerland", Iso3 = "CHE", Iso2 = "CH", NumericCode = "756", PhoneCode = "41", Capital = "Bern", Currency = new Currency(code: "CHF", name: "Swiss franc", symbol: "CHf"), Region = new Region(name: "Europe", subregion: "Western Europe"), GeoLocation = new GeoLocation(latitude: 47.00000000, longitude: 8.00000000)}
        , new Country { Id = 215, Name = "Syria", Iso3 = "SYR", Iso2 = "SY", NumericCode = "760", PhoneCode = "963", Capital = "Damascus", Currency = new Currency(code: "SYP", name: "Syrian pound", symbol: "LS"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 35.00000000, longitude: 38.00000000)}
        , new Country { Id = 216, Name = "Taiwan", Iso3 = "TWN", Iso2 = "TW", NumericCode = "158", PhoneCode = "886", Capital = "Taipei", Currency = new Currency(code: "TWD", name: "New Taiwan dollar", symbol: "$"), Region = new Region(name: "Asia", subregion: "Eastern Asia"), GeoLocation = new GeoLocation(latitude: 23.50000000, longitude: 121.00000000)}
        , new Country { Id = 217, Name = "Tajikistan", Iso3 = "TJK", Iso2 = "TJ", NumericCode = "762", PhoneCode = "992", Capital = "Dushanbe", Currency = new Currency(code: "TJS", name: "Tajikistani somoni", symbol: "SM"), Region = new Region(name: "Asia", subregion: "Central Asia"), GeoLocation = new GeoLocation(latitude: 39.00000000, longitude: 71.00000000)}
        , new Country { Id = 218, Name = "Tanzania", Iso3 = "TZA", Iso2 = "TZ", NumericCode = "834", PhoneCode = "255", Capital = "Dodoma", Currency = new Currency(code: "TZS", name: "Tanzanian shilling", symbol: "TSh"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -6.00000000, longitude: 35.00000000)}
        , new Country { Id = 219, Name = "Thailand", Iso3 = "THA", Iso2 = "TH", NumericCode = "764", PhoneCode = "66", Capital = "Bangkok", Currency = new Currency(code: "THB", name: "Thai baht", symbol: "฿"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 15.00000000, longitude: 100.00000000)}
        , new Country { Id = 17, Name = "The Bahamas", Iso3 = "BHS", Iso2 = "BS", NumericCode = "044", PhoneCode = "+1-242", Capital = "Nassau", Currency = new Currency(code: "BSD", name: "Bahamian dollar", symbol: "B$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 24.25000000, longitude: -76.00000000)}
        , new Country { Id = 220, Name = "Togo", Iso3 = "TGO", Iso2 = "TG", NumericCode = "768", PhoneCode = "228", Capital = "Lome", Currency = new Currency(code: "XOF", name: "West African CFA franc", symbol: "CFA"), Region = new Region(name: "Africa", subregion: "Western Africa"), GeoLocation = new GeoLocation(latitude: 8.00000000, longitude: 1.16666666)}
        , new Country { Id = 221, Name = "Tokelau", Iso3 = "TKL", Iso2 = "TK", NumericCode = "772", PhoneCode = "690", Capital = "", Currency = new Currency(code: "NZD", name: "New Zealand dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -9.00000000, longitude: -172.00000000)}
        , new Country { Id = 222, Name = "Tonga", Iso3 = "TON", Iso2 = "TO", NumericCode = "776", PhoneCode = "676", Capital = "Nuku'alofa", Currency = new Currency(code: "TOP", name: "Tongan paʻanga", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -20.00000000, longitude: -175.00000000)}
        , new Country { Id = 223, Name = "Trinidad And Tobago", Iso3 = "TTO", Iso2 = "TT", NumericCode = "780", PhoneCode = "+1-868", Capital = "Port of Spain", Currency = new Currency(code: "TTD", name: "Trinidad and Tobago dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 11.00000000, longitude: -61.00000000)}
        , new Country { Id = 224, Name = "Tunisia", Iso3 = "TUN", Iso2 = "TN", NumericCode = "788", PhoneCode = "216", Capital = "Tunis", Currency = new Currency(code: "TND", name: "Tunisian dinar", symbol: "ت.د"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 34.00000000, longitude: 9.00000000)}
        , new Country { Id = 225, Name = "Turkey", Iso3 = "TUR", Iso2 = "TR", NumericCode = "792", PhoneCode = "90", Capital = "Ankara", Currency = new Currency(code: "TRY", name: "Turkish lira", symbol: "₺"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 39.00000000, longitude: 35.00000000)}
        , new Country { Id = 226, Name = "Turkmenistan", Iso3 = "TKM", Iso2 = "TM", NumericCode = "795", PhoneCode = "993", Capital = "Ashgabat", Currency = new Currency(code: "TMT", name: "Turkmenistan manat", symbol: "T"), Region = new Region(name: "Asia", subregion: "Central Asia"), GeoLocation = new GeoLocation(latitude: 40.00000000, longitude: 60.00000000)}
        , new Country { Id = 227, Name = "Turks And Caicos Islands", Iso3 = "TCA", Iso2 = "TC", NumericCode = "796", PhoneCode = "+1-649", Capital = "Cockburn Town", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 21.75000000, longitude: -71.58333333)}
        , new Country { Id = 228, Name = "Tuvalu", Iso3 = "TUV", Iso2 = "TV", NumericCode = "798", PhoneCode = "688", Capital = "Funafuti", Currency = new Currency(code: "AUD", name: "Australian dollar", symbol: "$"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -8.00000000, longitude: 178.00000000)}
        , new Country { Id = 229, Name = "Uganda", Iso3 = "UGA", Iso2 = "UG", NumericCode = "800", PhoneCode = "256", Capital = "Kampala", Currency = new Currency(code: "UGX", name: "Ugandan shilling", symbol: "USh"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: 1.00000000, longitude: 32.00000000)}
        , new Country { Id = 230, Name = "Ukraine", Iso3 = "UKR", Iso2 = "UA", NumericCode = "804", PhoneCode = "380", Capital = "Kiev", Currency = new Currency(code: "UAH", name: "Ukrainian hryvnia", symbol: "₴"), Region = new Region(name: "Europe", subregion: "Eastern Europe"), GeoLocation = new GeoLocation(latitude: 49.00000000, longitude: 32.00000000)}
        , new Country { Id = 231, Name = "United Arab Emirates", Iso3 = "ARE", Iso2 = "AE", NumericCode = "784", PhoneCode = "971", Capital = "Abu Dhabi", Currency = new Currency(code: "AED", name: "United Arab Emirates dirham", symbol: "إ.د"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 24.00000000, longitude: 54.00000000)}
        , new Country { Id = 232, Name = "United Kingdom", Iso3 = "GBR", Iso2 = "GB", NumericCode = "826", PhoneCode = "44", Capital = "London", Currency = new Currency(code: "GBP", name: "British pound", symbol: "£"), Region = new Region(name: "Europe", subregion: "Northern Europe"), GeoLocation = new GeoLocation(latitude: 54.00000000, longitude: -2.00000000)}
        , new Country { Id = 233, Name = "United States", Iso3 = "USA", Iso2 = "US", NumericCode = "840", PhoneCode = "1", Capital = "Washington", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Northern America"), GeoLocation = new GeoLocation(latitude: 38.00000000, longitude: -97.00000000)}
        , new Country { Id = 234, Name = "United States Minor Outlying Islands", Iso3 = "UMI", Iso2 = "UM", NumericCode = "581", PhoneCode = "1", Capital = "", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Northern America"), GeoLocation = new GeoLocation(latitude: 0.00000000, longitude: 0.00000000)}
        , new Country { Id = 235, Name = "Uruguay", Iso3 = "URY", Iso2 = "UY", NumericCode = "858", PhoneCode = "598", Capital = "Montevideo", Currency = new Currency(code: "UYU", name: "Uruguayan peso", symbol: "$"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: -33.00000000, longitude: -56.00000000)}
        , new Country { Id = 236, Name = "Uzbekistan", Iso3 = "UZB", Iso2 = "UZ", NumericCode = "860", PhoneCode = "998", Capital = "Tashkent", Currency = new Currency(code: "UZS", name: "Uzbekistani soʻm", symbol: "лв"), Region = new Region(name: "Asia", subregion: "Central Asia"), GeoLocation = new GeoLocation(latitude: 41.00000000, longitude: 64.00000000)}
        , new Country { Id = 237, Name = "Vanuatu", Iso3 = "VUT", Iso2 = "VU", NumericCode = "548", PhoneCode = "678", Capital = "Port Vila", Currency = new Currency(code: "VUV", name: "Vanuatu vatu", symbol: "VT"), Region = new Region(name: "Oceania", subregion: "Melanesia"), GeoLocation = new GeoLocation(latitude: -16.00000000, longitude: 167.00000000)}
        , new Country { Id = 238, Name = "Vatican City State (Holy See)", Iso3 = "VAT", Iso2 = "VA", NumericCode = "336", PhoneCode = "379", Capital = "Vatican City", Currency = new Currency(code: "EUR", name: "Euro", symbol: "€"), Region = new Region(name: "Europe", subregion: "Southern Europe"), GeoLocation = new GeoLocation(latitude: 41.90000000, longitude: 12.45000000)}
        , new Country { Id = 239, Name = "Venezuela", Iso3 = "VEN", Iso2 = "VE", NumericCode = "862", PhoneCode = "58", Capital = "Caracas", Currency = new Currency(code: "VEF", name: "Bolívar", symbol: "Bs"), Region = new Region(name: "Americas", subregion: "South America"), GeoLocation = new GeoLocation(latitude: 8.00000000, longitude: -66.00000000)}
        , new Country { Id = 240, Name = "Vietnam", Iso3 = "VNM", Iso2 = "VN", NumericCode = "704", PhoneCode = "84", Capital = "Hanoi", Currency = new Currency(code: "VND", name: "Vietnamese đồng", symbol: "₫"), Region = new Region(name: "Asia", subregion: "South-Eastern Asia"), GeoLocation = new GeoLocation(latitude: 16.16666666, longitude: 107.83333333)}
        , new Country { Id = 241, Name = "Virgin Islands (British)", Iso3 = "VGB", Iso2 = "VG", NumericCode = "092", PhoneCode = "+1-284", Capital = "Road Town", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.43138300, longitude: -64.62305000)}
        , new Country { Id = 242, Name = "Virgin Islands (US)", Iso3 = "VIR", Iso2 = "VI", NumericCode = "850", PhoneCode = "+1-340", Capital = "Charlotte Amalie", Currency = new Currency(code: "USD", name: "United States dollar", symbol: "$"), Region = new Region(name: "Americas", subregion: "Caribbean"), GeoLocation = new GeoLocation(latitude: 18.34000000, longitude: -64.93000000)}
        , new Country { Id = 243, Name = "Wallis And Futuna Islands", Iso3 = "WLF", Iso2 = "WF", NumericCode = "876", PhoneCode = "681", Capital = "Mata Utu", Currency = new Currency(code: "XPF", name: "CFP franc", symbol: "₣"), Region = new Region(name: "Oceania", subregion: "Polynesia"), GeoLocation = new GeoLocation(latitude: -13.30000000, longitude: -176.20000000)}
        , new Country { Id = 244, Name = "Western Sahara", Iso3 = "ESH", Iso2 = "EH", NumericCode = "732", PhoneCode = "212", Capital = "El-Aaiun", Currency = new Currency(code: "MAD", name: "Moroccan Dirham", symbol: "MAD"), Region = new Region(name: "Africa", subregion: "Northern Africa"), GeoLocation = new GeoLocation(latitude: 24.50000000, longitude: -13.00000000)}
        , new Country { Id = 245, Name = "Yemen", Iso3 = "YEM", Iso2 = "YE", NumericCode = "887", PhoneCode = "967", Capital = "Sanaa", Currency = new Currency(code: "YER", name: "Yemeni rial", symbol: "﷼"), Region = new Region(name: "Asia", subregion: "Western Asia"), GeoLocation = new GeoLocation(latitude: 15.00000000, longitude: 48.00000000)}
        , new Country { Id = 246, Name = "Zambia", Iso3 = "ZMB", Iso2 = "ZM", NumericCode = "894", PhoneCode = "260", Capital = "Lusaka", Currency = new Currency(code: "ZMW", name: "Zambian kwacha", symbol: "ZK"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -15.00000000, longitude: 30.00000000)}
        , new Country { Id = 247, Name = "Zimbabwe", Iso3 = "ZWE", Iso2 = "ZW", NumericCode = "716", PhoneCode = "263", Capital = "Harare", Currency = new Currency(code: "ZWL", name: "Zimbabwe Dollar", symbol: "$"), Region = new Region(name: "Africa", subregion: "Eastern Africa"), GeoLocation = new GeoLocation(latitude: -20.00000000, longitude: 30.00000000)}
        });
    }
}
